apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: registryonly-mode
  namespace: istio-system
spec:
  meshConfig:
    outboundTrafficPolicy:
      mode: REGISTRY_ONLY
    accessLogFile: /dev/stdout
