apiVersion: v1
kind: ConfigMap
metadata:
  name: ratelimit-config
data:
  config.yaml: |
    domain: advertisement-ratelimit
    descriptors:
      - key: PATH
        value: "/ad"
        rate_limit:
          unit: minute
          requests_per_unit: 3
      - key: PATH
        rate_limit:
          unit: minute
          requests_per_unit: 100

