apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-route
spec:
  gateways:
  - istio-system/weather-gateway
  hosts:
  - wistio.cc
  http:
  - route:
    - destination:
        host: frontend
        subset: v1
